ruff:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  fl1_position_controller:
    type: effort_controllers/JointPositionController
    joint: FL1_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  fl2_position_controller:
    type: effort_controllers/JointPositionController
    joint: FL2_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  fl3_position_controller:
    type: effort_controllers/JointPositionController
    joint: FL3_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  fr1_position_controller:
    type: effort_controllers/JointPositionController
    joint: FR1_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  fr2_position_controller:
    type: effort_controllers/JointPositionController
    joint: FR2_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  fr3_position_controller:
    type: effort_controllers/JointPositionController
    joint: FR3_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  rl1_position_controller:
    type: effort_controllers/JointPositionController
    joint: RL1_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  rl2_position_controller:
    type: effort_controllers/JointPositionController
    joint: RL2_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  rl3_position_controller:
    type: effort_controllers/JointPositionController
    joint: RL3_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  rr1_position_controller:
    type: effort_controllers/JointPositionController
    joint: RR1_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  rr2_position_controller:
    type: effort_controllers/JointPositionController
    joint: RR2_
    pid: {p: 300.0,i: 1.0, d: 20.0}
  rr3_position_controller:
    type: effort_controllers/JointPositionController
    joint: RR3_
    pid: {p: 300.0,i: 1.0, d: 20.0}
