scene:
  env_spacing: 30
  rows: 1
  cols: 1
  joint_names:
    - FL1_
    - FL2_
    - FL3_
    - FR1_
    - FR2_
    - FR3_
    - RL1_
    - RL2_
    - RL3_
    - RR1_
    - RR2_
    - RR3_
env_config:
  sim_dt: 0.001
  decimation: 10
  max_episode_length: 1000
  episode_length_s: 10
  seed: 42

train:
  num_envs: 8192
  num_iterations: 400
  rows: 10
  cols: 10
  total_timesteps: 98e6
  n_steps: 128
  batch_size: 65_536
  learning_rate:
    start: 3.5e-4
    end: 3.0e-4
    end_fraction: 1.0
  clip_range: 0.2
  gamma: 0.992
  ent_coef: 0.0025
  n_epochs: 10
  target_kl: 0.015
eval:
  num_envs: 1
  rows: 1
  cols: 1

save_config:
  save_path: ../../models/isaac_models/
  save_prefix: ruu_ppo_model
